// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GroceryApi.Models;

public partial class Grocery
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int CategoryId { get; set; }

    public double DefaultAmount { get; set; }

    public string DefaultUnit { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<StoreArea> StoreAreas { get; set; } = new List<StoreArea>();
}