// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GroceryApi.Models;

public partial class StoreArea
{
    public int Id { get; set; }

    public int StoreId { get; set; }

    public string Name { get; set; }

    public virtual Store Store { get; set; }

    public virtual ICollection<Grocery> Groceries { get; set; } = new List<Grocery>();
}